# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WantedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'FirstName')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name=b'LastName')),
                ('photo', models.ImageField(blank=True, upload_to=b'img/', verbose_name=b'Photo')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name=b'Birthday')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name=b'Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name=b'Email')),
                ('note', models.TextField(blank=True, verbose_name=b'Note')),
            ],
        ),
    ]
