# Generated by Django 2.1.2 on 2018-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedperson',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='Photo'),
        ),
    ]
