# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name=b'LastName'),
        ),
    ]
