# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedperson',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'city'),
        ),
        migrations.AddField(
            model_name='wantedperson',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Country'),
        ),
    ]
