# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0002_auto_20180520_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedperson',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'img/', verbose_name=b'Photo'),
        ),
    ]
