# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0002_auto_20180603_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name=b'comment')),
                ('date', models.DateField(verbose_name=b'comment_date')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peoplesWDB.WantedPerson')),
            ],
        ),
    ]
