# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0003_auto_20180520_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedperson',
            name='first_name',
            field=models.CharField(error_messages={b'required': b'a'}, max_length=50, verbose_name=b'FirstName'),
        ),
        migrations.AlterField(
            model_name='wantedperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'LastName'),
        ),
    ]
