# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0004_auto_20180601_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedperson',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=b'Birthday'),
        ),
        migrations.AlterField(
            model_name='wantedperson',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name=b'FirstName'),
        ),
    ]
