# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-29 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peoplesWDB', '0005_auto_20180630_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedperson',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
