# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0007_auto_20180809_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'img/', verbose_name=b'Ptofile photo'),
        ),
    ]
