# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplesWDB', '0008_auto_20180809_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=b'profile_img/', verbose_name=b'Ptofile photo'),
        ),
    ]
